import { Language } from './types';

export const API_BASE_URL = 'http://localhost:5000/api';
export const CURRENT_FARMER_ID = 1;

export const APP_ROUTES = {
  HOME: '/',
  VOICE: '/voice',
  ACTIVITY: '/activity',
  FINANCE: '/finance',
  SCHEMES: '/schemes',
};

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    appName: "Krishi Sahayak",
    greeting: "Hello Farmer!",
    prompt: "What would you like to record today?",
    voiceBtn: "Record by Voice",
    voiceSub: "Seeds, Fertilizer, Water, Expense",
    diary: "Farm Diary",
    diarySub: "View past activities",
    finance: "Finance",
    financeSub: "Income & Expenses",
    schemes: "Schemes & Weather",
    schemesSub: "Govt Benefits",
    tabWeather: "Weather & Crops",
    tabSchemes: "Govt Schemes",
    navHome: "Home",
    navWork: "Work",
    navSpeak: "Speak",
    navMoney: "Money",
    navPlan: "Plan",
    listening: "Listening...",
    processing: "Processing...",
    speakNow: "Speak now",
    speakHint: "e.g., 'Sowed Tomato in 2 acres today'",
    speakHint2: "or: 'Bought fertilizer for 500 rupees'",
    micHint: "Tap mic to speak",
    stop: "Stop",
    success: "Success!",
    saved: "Information saved successfully.",
    retry: "Try Again",
    confirmTitle: "You said:",
    aiUnderstood: "AI Understood:",
    incorrect: "Incorrect",
    correct: "Confirm",
    weatherAlert: "Weather Alerts",
    fiveDayForecast: "5-Day Forecast",
    cropRec: "Crop Recommendation",
    govtSchemes: "Govt Schemes",
    income: "Income",
    expense: "Expense",
    netProfit: "Net Profit",
    totalIncome: "Total Income",
    totalExpense: "Total Expense",
    noAlerts: "No active alerts.",
    loading: "Loading...",
    noData: "No data found.",
    crop: "Crop",
    amount: "Amount",
    activity: "Activity",
    acres: "Acres",
    errorGeneric: "Something went wrong.",
    errorBrowser: "Your browser does not support voice.",
    suitabilityHigh: "Highly Suitable",
    suitabilityMed: "Moderately Suitable",
    suitabilityLow: "Low Suitability",
    currentLocation: "Location",
    // Crop Translations
    crop_Rice: "Rice",
    crop_Wheat: "Wheat",
    crop_Maize: "Maize",
    crop_Sugarcane: "Sugarcane",
    crop_Cotton: "Cotton",
    crop_Pulses: "Pulses"
  },
  [Language.HINDI]: {
    appName: "कृषि सहायक",
    greeting: "नमस्ते किसान भाई!",
    prompt: "आज आप क्या दर्ज करना चाहेंगे?",
    voiceBtn: "बोलकर दर्ज करें",
    voiceSub: "बीज, खाद, पानी, खर्चा",
    diary: "खेती डायरी",
    diarySub: "पिछले काम देखें",
    finance: "हिसाब किताब",
    financeSub: "खर्चा और मुनाफा",
    schemes: "योजना और मौसम",
    schemesSub: "सरकारी लाभ",
    tabWeather: "मौसम और फसलें",
    tabSchemes: "सरकारी योजनाएं",
    navHome: "मुख्य",
    navWork: "कार्य",
    navSpeak: "बोलें",
    navMoney: "वित्त",
    navPlan: "योजना",
    listening: "सुन रहा हूँ...",
    processing: "समझ रहा हूँ...",
    speakNow: "बोलकर बताएं",
    speakHint: "जैसे: 'आज 2 एकड़ में टमाटर लगाए'",
    speakHint2: "या: '500 रुपये की खाद खरीदी'",
    micHint: "माइक दबाएं और बोलें",
    stop: "रुकें",
    success: "सफल!",
    saved: "जानकारी सुरक्षित कर ली गई है।",
    retry: "पुनः प्रयास करें",
    confirmTitle: "आपने कहा:",
    aiUnderstood: "AI ने समझा:",
    incorrect: "सुधारें",
    correct: "पुष्टि करें",
    weatherAlert: "मौसम चेतावनी",
    fiveDayForecast: "5-दिवसीय पूर्वानुमान",
    cropRec: "उपयुक्त फसलें",
    govtSchemes: "सरकारी योजनाएं",
    income: "आय",
    expense: "व्यय",
    netProfit: "कुल लाभ",
    totalIncome: "कुल आय",
    totalExpense: "कुल व्यय",
    noAlerts: "कोई चेतावनी नहीं।",
    loading: "प्रतीक्षा करें...",
    noData: "कोई जानकारी नहीं",
    crop: "फसल",
    amount: "धनराशि",
    activity: "गतिविधि",
    acres: "एकड़",
    errorGeneric: "त्रुटि हुई।",
    errorBrowser: "ब्राउज़र सपोर्ट नहीं करता।",
    suitabilityHigh: "अत्यधिक उपयुक्त",
    suitabilityMed: "मध्यम उपयुक्त",
    suitabilityLow: "कम उपयुक्त",
    currentLocation: "स्थान",
    // Crop Translations
    crop_Rice: "चावल (धान)",
    crop_Wheat: "गेहूं",
    crop_Maize: "मक्का",
    crop_Sugarcane: "गन्ना",
    crop_Cotton: "कपास",
    crop_Pulses: "दालें"
  },
  [Language.MARATHI]: {
    appName: "कृषी सहाय्यक",
    greeting: "नमस्कार शेतकरी दादा!",
    prompt: "आज आपण काय नोंदवू इच्छिता?",
    voiceBtn: "बोलून नोंद करा",
    voiceSub: "बियाणे, खत, पाणी, खर्च",
    diary: "शेती डायरी",
    diarySub: "मागील कामे पहा",
    finance: "आर्थिक व्यवहार",
    financeSub: "खर्च आणि नफा",
    schemes: "योजना आणि हवामान",
    schemesSub: "सरकारी लाभ",
    tabWeather: "हवामान आणि पिके",
    tabSchemes: "सरकारी योजना",
    navHome: "मुख्य",
    navWork: "कामे",
    navSpeak: "बोला",
    navMoney: "हिशोब",
    navPlan: "नियोजन",
    listening: "ऐकत आहे...",
    processing: "समजून घेत आहे...",
    speakNow: "बोलून सांगा",
    speakHint: "उदा: 'आज २ एकरात टोमॅटो लावले'",
    speakHint2: "किंवा: '५०० रुपयांचे खत आणले'",
    micHint: "माईक दाबा आणि बोला",
    stop: "थांबा",
    success: "यशस्वी!",
    saved: "माहिती जतन केली आहे.",
    retry: "पुन्हा प्रयत्न करा",
    confirmTitle: "तुम्ही म्हणालात:",
    aiUnderstood: "AI ला समजले:",
    incorrect: "चूक आहे",
    correct: "बरोबर आहे",
    weatherAlert: "हवामान इशारा",
    fiveDayForecast: "५-दिवसीय हवामान",
    cropRec: "पिकाचा सल्ला",
    govtSchemes: "सरकारी योजना",
    income: "उत्पन्न",
    expense: "खर्च",
    netProfit: "निव्वळ नफा",
    totalIncome: "एकूण उत्पन्न",
    totalExpense: "एकूण खर्च",
    noAlerts: "कोणताही इशारा नाही.",
    loading: "लोड होत आहे...",
    noData: "माहिती उपलब्ध नाही",
    crop: "पीक",
    amount: "रक्कम",
    activity: "काम",
    acres: "एकड़",
    errorGeneric: "जतन करू शकलो नाही.",
    errorBrowser: "तुमचा ब्राउझर व्हॉईस सपोर्ट करत नाही.",
    suitabilityHigh: "अत्यंत योग्य",
    suitabilityMed: "मध्यम योग्य",
    suitabilityLow: "कमी योग्य",
    currentLocation: "स्थान",
    // Crop Translations
    crop_Rice: "तांदूळ (धान)",
    crop_Wheat: "गहू",
    crop_Maize: "मका",
    crop_Sugarcane: "ऊस",
    crop_Cotton: "कापूस",
    crop_Pulses: "डाळी"
  }
};
